In [2]:
%pip install pandas
%pip install openpyxl

Requirement already satisfied: pandas in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Danny\My Drive\network_meta-analysis\venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

df = pd.read_excel(f"./data/study_results.xlsx")

In [2]:
df.head()

,id,study,subgroup,outcome,data_type,ni,yi,sdi,TE,seTE,age,male,female,follow_up
0,6,"Anz et al., 2023",BPTB,graft rupture,dichotomous,8,0.0,0.18,NaN,NaN,27.6,3.0,7.0,12.0
1,6,"Anz et al., 2023",HT,graft rupture,dichotomous,8,0.0,0.18,NaN,NaN,27.6,3.0,7.0,12.0
2,43,"Kautzner et al., 2015",BPTB,graft rupture,dichotomous,74,0.0,0.06,NaN,NaN,26.0,0.0,73.0,24.0
3,43,"Kautzner et al., 2015",HT,graft rupture,dichotomous,73,2.0,0.30,NaN,NaN,26.0,0.0,73.0,24.0
4,49,"Laxdal et al., 2005",BPTB,graft rupture,dichotomous,40,1.0,0.24,NaN,NaN,25.0,NaN,NaN,26.0

In [30]:
def pivot(df, index, id = "id"):
    df = pd.read_csv(f"./data/extracted/csv/{df}.csv", encoding = "utf-8").fillna("")
    df["id"] = df[f"{id}"] 
    columns = df.drop(columns = [index, "id"])
    values = df.columns
    
    df["group"] = df.groupby([f"{id}"]).cumcount() + 1
        
    wide = (
        df.pivot(
            index= "id",
            columns="group",
            values= values
        )
    ).reset_index()
    
    
    wide.columns = [
        f"{name}{group}" for name, group in wide.columns
    ]
        
    
    #    df = df.drop(columns = f"{index}2").fillna("")
    df = df.reset_index()
    return df

In [51]:
values

Index(['id', 'study', 'subgroup', 'outcome', 'data_type', 'ni', 'yi', 'sdi',
       'age_mean', 'age_sd', 'male', 'female', 'follow-up_mo', 'follow-up_yr',
       'screening'],
      dtype='str')

In [72]:


df = pd.read_csv(f"./data/extracted/csv/data.csv", encoding = "utf-8").fillna("")

df = df.drop(columns =  ["min", "max", "q1", "q3", "median"])
columns = df.drop(columns = ["id"])
values = df.columns

df["group"] = df.groupby(["study"]).cumcount() + 1

wide = (
    df.pivot(
        index= ["study"],
        columns = "group",
        values= ['ni', 'yi', 'sdi','age_mean', 'age_sd', 'male', 'female', 'follow-up_mo', 'follow-up_yr']
    )
).reset_index()
    
wide = wide.fillna("")
#    df = df.drop(columns = f"{index}2").fillna("")
wide = wide.reset_index()

wide.head()

      index                  study    ni                                      \
group                                  1     2     3     4     5     6     7
0         0   Ageberg et al., 2009  16.0  20.0
1         1  Aglietti et al., 2004  60.0  60.0  60.0  60.0  60.0  60.0
2         2    Ahldén et al., 2009              25.0  22.0  25.0  22.0  25.0
3         3   Akelman et al., 2016
4         4  Anderson et al., 2001              35.0  33.0  35.0  33.0

             ... follow-up_yr
group     8  ...            5    6    7    8 9 10 11 12 13 14
0            ...
1            ...          2.0  2.0
2      22.0  ...          7.5  7.5  7.5  7.5
3            ...
4            ...          2.9  2.9

[5 rows x 128 columns]

In [50]:
import pandas as pd
data = pivot("data", "study", "id")
data.head()

,index,id,study,subgroup,outcome,data_type,ni,yi,sdi,min,...,q3,max,age_mean,age_sd,male,female,follow-up_mo,follow-up_yr,screening,group
0,0,6,"Anz et al., 2023",BPTB,graft rupture,dichotomous,8.0,0.0,0.18,,...,,,29.4,7.34,4.0,6.0,12.0,1.0,included,1
1,1,6,"Anz et al., 2023",HT,graft rupture,dichotomous,8.0,0.0,0.18,,...,,,29.4,7.34,4.0,6.0,12.0,1.0,included,2
2,2,12,"Bi et al., 2018",HT,graft rupture,dichotomous,,,,,...,,,27.9,6.7,31.0,31.0,30.0,2.5,excluded,1
3,3,12,"Bi et al., 2018",PLT,graft rupture,dichotomous,,,,,...,,,27.9,6.7,31.0,31.0,30.0,2.5,excluded,2
4,4,22,"Cruz et al., 2022",HT,graft rupture,dichotomous,,,,,...,,,,,,,,,excluded,1

In [5]:
continuous = df[df["data_type"] == "continuous"].to_csv(f"./data/continuous.csv")
dichotomous = df[df["data_type"] == "dichotomous"].to_csv(f"./data/dichotomous.csv")

<a id="meta-analysis"></a>

<h1 align="center" style="font-family:Times New Roman;font-variant:small-caps;">Meta-Analysis</h1>

<a id="meta-analysis"></a>

<h2 align="center" style="font-family:Times New Roman;font-variant:small-caps;">Network Meta-Analysis</h2>

- [Network Meta-Analysis in R](./R/R.ipynb)
- [Network Meta-Analysis using Python](./python/python.ipynb)